# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/Kartikay/neuro/MultiNEAT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/Kartikay/neuro/MultiNEAT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Kartikay/neuro/MultiNEAT/CMakeFiles /home/Kartikay/neuro/MultiNEAT/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/Kartikay/neuro/MultiNEAT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MultiNEAT

# Build rule for target.
MultiNEAT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 MultiNEAT
.PHONY : MultiNEAT

# fast build rule for target.
MultiNEAT/fast:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/build
.PHONY : MultiNEAT/fast

src/Genome.o: src/Genome.cpp.o

.PHONY : src/Genome.o

# target to build an object file
src/Genome.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Genome.cpp.o
.PHONY : src/Genome.cpp.o

src/Genome.i: src/Genome.cpp.i

.PHONY : src/Genome.i

# target to preprocess a source file
src/Genome.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Genome.cpp.i
.PHONY : src/Genome.cpp.i

src/Genome.s: src/Genome.cpp.s

.PHONY : src/Genome.s

# target to generate assembly for a file
src/Genome.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Genome.cpp.s
.PHONY : src/Genome.cpp.s

src/Innovation.o: src/Innovation.cpp.o

.PHONY : src/Innovation.o

# target to build an object file
src/Innovation.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Innovation.cpp.o
.PHONY : src/Innovation.cpp.o

src/Innovation.i: src/Innovation.cpp.i

.PHONY : src/Innovation.i

# target to preprocess a source file
src/Innovation.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Innovation.cpp.i
.PHONY : src/Innovation.cpp.i

src/Innovation.s: src/Innovation.cpp.s

.PHONY : src/Innovation.s

# target to generate assembly for a file
src/Innovation.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Innovation.cpp.s
.PHONY : src/Innovation.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/NeuralNetwork.o: src/NeuralNetwork.cpp.o

.PHONY : src/NeuralNetwork.o

# target to build an object file
src/NeuralNetwork.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/NeuralNetwork.cpp.o
.PHONY : src/NeuralNetwork.cpp.o

src/NeuralNetwork.i: src/NeuralNetwork.cpp.i

.PHONY : src/NeuralNetwork.i

# target to preprocess a source file
src/NeuralNetwork.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/NeuralNetwork.cpp.i
.PHONY : src/NeuralNetwork.cpp.i

src/NeuralNetwork.s: src/NeuralNetwork.cpp.s

.PHONY : src/NeuralNetwork.s

# target to generate assembly for a file
src/NeuralNetwork.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/NeuralNetwork.cpp.s
.PHONY : src/NeuralNetwork.cpp.s

src/Parameters.o: src/Parameters.cpp.o

.PHONY : src/Parameters.o

# target to build an object file
src/Parameters.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Parameters.cpp.o
.PHONY : src/Parameters.cpp.o

src/Parameters.i: src/Parameters.cpp.i

.PHONY : src/Parameters.i

# target to preprocess a source file
src/Parameters.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Parameters.cpp.i
.PHONY : src/Parameters.cpp.i

src/Parameters.s: src/Parameters.cpp.s

.PHONY : src/Parameters.s

# target to generate assembly for a file
src/Parameters.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Parameters.cpp.s
.PHONY : src/Parameters.cpp.s

src/PhenotypeBehavior.o: src/PhenotypeBehavior.cpp.o

.PHONY : src/PhenotypeBehavior.o

# target to build an object file
src/PhenotypeBehavior.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/PhenotypeBehavior.cpp.o
.PHONY : src/PhenotypeBehavior.cpp.o

src/PhenotypeBehavior.i: src/PhenotypeBehavior.cpp.i

.PHONY : src/PhenotypeBehavior.i

# target to preprocess a source file
src/PhenotypeBehavior.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/PhenotypeBehavior.cpp.i
.PHONY : src/PhenotypeBehavior.cpp.i

src/PhenotypeBehavior.s: src/PhenotypeBehavior.cpp.s

.PHONY : src/PhenotypeBehavior.s

# target to generate assembly for a file
src/PhenotypeBehavior.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/PhenotypeBehavior.cpp.s
.PHONY : src/PhenotypeBehavior.cpp.s

src/Population.o: src/Population.cpp.o

.PHONY : src/Population.o

# target to build an object file
src/Population.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Population.cpp.o
.PHONY : src/Population.cpp.o

src/Population.i: src/Population.cpp.i

.PHONY : src/Population.i

# target to preprocess a source file
src/Population.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Population.cpp.i
.PHONY : src/Population.cpp.i

src/Population.s: src/Population.cpp.s

.PHONY : src/Population.s

# target to generate assembly for a file
src/Population.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Population.cpp.s
.PHONY : src/Population.cpp.s

src/PythonBindings.o: src/PythonBindings.cpp.o

.PHONY : src/PythonBindings.o

# target to build an object file
src/PythonBindings.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/PythonBindings.cpp.o
.PHONY : src/PythonBindings.cpp.o

src/PythonBindings.i: src/PythonBindings.cpp.i

.PHONY : src/PythonBindings.i

# target to preprocess a source file
src/PythonBindings.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/PythonBindings.cpp.i
.PHONY : src/PythonBindings.cpp.i

src/PythonBindings.s: src/PythonBindings.cpp.s

.PHONY : src/PythonBindings.s

# target to generate assembly for a file
src/PythonBindings.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/PythonBindings.cpp.s
.PHONY : src/PythonBindings.cpp.s

src/Random.o: src/Random.cpp.o

.PHONY : src/Random.o

# target to build an object file
src/Random.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Random.cpp.o
.PHONY : src/Random.cpp.o

src/Random.i: src/Random.cpp.i

.PHONY : src/Random.i

# target to preprocess a source file
src/Random.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Random.cpp.i
.PHONY : src/Random.cpp.i

src/Random.s: src/Random.cpp.s

.PHONY : src/Random.s

# target to generate assembly for a file
src/Random.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Random.cpp.s
.PHONY : src/Random.cpp.s

src/Species.o: src/Species.cpp.o

.PHONY : src/Species.o

# target to build an object file
src/Species.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Species.cpp.o
.PHONY : src/Species.cpp.o

src/Species.i: src/Species.cpp.i

.PHONY : src/Species.i

# target to preprocess a source file
src/Species.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Species.cpp.i
.PHONY : src/Species.cpp.i

src/Species.s: src/Species.cpp.s

.PHONY : src/Species.s

# target to generate assembly for a file
src/Species.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Species.cpp.s
.PHONY : src/Species.cpp.s

src/Substrate.o: src/Substrate.cpp.o

.PHONY : src/Substrate.o

# target to build an object file
src/Substrate.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Substrate.cpp.o
.PHONY : src/Substrate.cpp.o

src/Substrate.i: src/Substrate.cpp.i

.PHONY : src/Substrate.i

# target to preprocess a source file
src/Substrate.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Substrate.cpp.i
.PHONY : src/Substrate.cpp.i

src/Substrate.s: src/Substrate.cpp.s

.PHONY : src/Substrate.s

# target to generate assembly for a file
src/Substrate.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Substrate.cpp.s
.PHONY : src/Substrate.cpp.s

src/Utils.o: src/Utils.cpp.o

.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i

.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s

.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/MultiNEAT.dir/build.make CMakeFiles/MultiNEAT.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MultiNEAT"
	@echo "... src/Genome.o"
	@echo "... src/Genome.i"
	@echo "... src/Genome.s"
	@echo "... src/Innovation.o"
	@echo "... src/Innovation.i"
	@echo "... src/Innovation.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/NeuralNetwork.o"
	@echo "... src/NeuralNetwork.i"
	@echo "... src/NeuralNetwork.s"
	@echo "... src/Parameters.o"
	@echo "... src/Parameters.i"
	@echo "... src/Parameters.s"
	@echo "... src/PhenotypeBehavior.o"
	@echo "... src/PhenotypeBehavior.i"
	@echo "... src/PhenotypeBehavior.s"
	@echo "... src/Population.o"
	@echo "... src/Population.i"
	@echo "... src/Population.s"
	@echo "... src/PythonBindings.o"
	@echo "... src/PythonBindings.i"
	@echo "... src/PythonBindings.s"
	@echo "... src/Random.o"
	@echo "... src/Random.i"
	@echo "... src/Random.s"
	@echo "... src/Species.o"
	@echo "... src/Species.i"
	@echo "... src/Species.s"
	@echo "... src/Substrate.o"
	@echo "... src/Substrate.i"
	@echo "... src/Substrate.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

